"""
Adversarial & Regression Test Suite for OmniCache Architecture Remediation.
Verifies:
1. Cryptographic PII Salted Isolation (No cross-user token collision)
2. Tool Replay TTL Expiration Enforcement
3. Model Family Isolation in Semantic Cache (No cross-model contamination)
4. Speculative Model Cascade Opt-in Enforcement & Response Disclosures
5. Virtual Key Manager Reject Unregistered Keys (No auto-registration)
"""

import unittest
import time
from core.privacy_shield import privacy_shield
from server.tool_replayer import tool_cache
from core.vector_cache import DualTierCache, get_model_family
from server.cascade_router import cascade_router
from server.quotas import quota_manager
from starlette.testclient import TestClient
from server.gateway import app

class TestSecurityRemediation(unittest.TestCase):
    def setUp(self):
        self.client = TestClient(app)

    def test_01_pii_salted_cross_user_isolation(self):
        """Verify different user emails generate completely distinct HMAC tokens."""
        text_a = "Contact alice@company-a.com"
        text_b = "Contact bob@company-b.com"

        sanitized_a, token_map_a, count_a = privacy_shield.sanitize_text(text_a)
        sanitized_b, token_map_b, count_b = privacy_shield.sanitize_text(text_b)

        self.assertEqual(count_a, 1)
        self.assertEqual(count_b, 1)

        token_a = list(token_map_a.keys())[0]
        token_b = list(token_map_b.keys())[0]

        # Critical: Tokens MUST NOT collide (unlike legacy [REDACTED_EMAIL_1])
        self.assertNotEqual(token_a, token_b)
        self.assertIn("[REDACTED_EMAIL_", token_a)
        self.assertIn("[REDACTED_EMAIL_", token_b)

    def test_02_tool_replay_ttl_expiration(self):
        """Verify expired tool calls return MISS and are evicted."""
        tool_name = "git_diff"
        args = {"file": "main.py"}
        output = "+ print('hello world')"

        # Store with 1 second TTL
        tool_cache.store_tool_call(tool_name, args, output, ttl_seconds=1)

        # Immediate lookup -> HIT
        is_hit, cached_out, _ = tool_cache.lookup_tool_call(tool_name, args)
        self.assertTrue(is_hit)
        self.assertEqual(cached_out, output)

        # Wait for TTL expiry
        time.sleep(1.1)

        # Lookup after expiry -> MISS (must be evicted)
        is_hit_expired, cached_out_expired, _ = tool_cache.lookup_tool_call(tool_name, args)
        self.assertFalse(is_hit_expired)
        self.assertIsNone(cached_out_expired)

    def test_03_model_family_semantic_isolation(self):
        """Verify semantic cache strictly isolates models across vendor families."""
        cache = DualTierCache()

        # Cache a response generated by Gemini Flash
        gemini_payload = {
            "model": "gemini-2.5-flash",
            "messages": [{"role": "user", "content": "How do I reverse a string in python?"}],
            "temperature": 0.0
        }
        gemini_resp = {"choices": [{"message": {"content": "text[::-1] (from Gemini)"}}]}
        cache.store(gemini_payload, gemini_resp, org_id="tenant_iso")

        # Now query with GPT-4o with semantically similar prompt
        gpt_payload = {
            "model": "gpt-4o",
            "messages": [{"role": "user", "content": "Tell me how to reverse a string in python"}],
            "temperature": 0.0
        }

        # Must MISS because model families (google-gemini-flash vs openai-gpt4o) do NOT match
        status, entry, sim, reason = cache.lookup(gpt_payload, org_id="tenant_iso")
        self.assertEqual(status, "MISS")
        self.assertIn("MISS_MODEL_FAMILY_MISMATCH", reason)

    def test_04_cascade_opt_in_governance(self):
        """Verify cascade router does NOT substitute models unless caller explicitly opts in."""
        payload = {
            "messages": [{"role": "user", "content": "Capitalize: hello"}]
        }

        # Default (allow_cascade=False) -> MUST retain requested model
        model_default, tier_def, comp_def, cascaded_def, reason_def = cascade_router.evaluate_route(
            "gpt-4o", payload, allow_cascade=False
        )
        self.assertEqual(model_default, "gpt-4o")
        self.assertFalse(cascaded_def)
        self.assertEqual(reason_def, "cascade_opt_in_disabled")

        # Opt-in enabled (allow_cascade=True) -> Can cascade trivial queries
        model_opted, tier_opt, comp_opt, cascaded_opt, reason_opt = cascade_router.evaluate_route(
            "gpt-4o", payload, allow_cascade=True
        )
        self.assertEqual(model_opted, "gemini-2.5-flash")
        self.assertTrue(cascaded_opt)

    def test_05_unregistered_key_rejected(self):
        """Verify VirtualKeyManager rejects unknown keys and does NOT auto-register them."""
        # Unrecognized random key
        allowed, reason, info = quota_manager.check_authorization("unrecognized_random_key_999")
        self.assertFalse(allowed)
        self.assertIsNone(info)
        self.assertIn("Unauthorized", reason)

    def test_06_circuit_breaker_telemetry_in_gateway(self):
        """Verify /healthz and /v1/cache/stats report live circuit breaker status."""
        client = TestClient(app)
        res_health = client.get("/healthz")
        self.assertEqual(res_health.status_code, 200)
        data = res_health.json()
        self.assertIn("circuit_breaker", data)
        self.assertIn("openai", data["circuit_breaker"])
        self.assertIn("anthropic", data["circuit_breaker"])
        self.assertIn("google", data["circuit_breaker"])

        # Check in /v1/cache/stats
        res_stats = client.get("/v1/cache/stats")
        self.assertEqual(res_stats.status_code, 200)
        stats_data = res_stats.json()
        self.assertIn("circuit_breaker", stats_data["enterprise_engine"])

    def test_07_dynamic_salt_uniqueness(self):
        """Verify privacy salt is dynamically generated and not a static public constant."""
        from core.config import config
        self.assertTrue(len(config.PRIVACY_SALT) >= 32)
        self.assertNotEqual(config.PRIVACY_SALT, "OmniCache-Production-Salt-2025-V2")
        self.assertNotEqual(config.PRIVACY_SALT, "default_salt")

    def test_08_admin_endpoints_require_admin_privileges(self):
        """Verify tenant keys cannot access /v1/enterprise/quotas or /v1/cache/export."""
        client = TestClient(app)
        quota_manager.register_key("standard_tenant_key", team_name="Tenant Team", org_id="tenant_x", role="tenant")
        
        # Accessing quotas as tenant should be rejected
        res_quotas = client.get("/v1/enterprise/quotas", headers={"x-api-key": "standard_tenant_key"})
        self.assertEqual(res_quotas.status_code, 403)

        # Accessing export as tenant should be rejected
        res_export = client.get("/v1/cache/export", headers={"x-api-key": "standard_tenant_key"})
        self.assertEqual(res_export.status_code, 403)

if __name__ == "__main__":
    unittest.main()
