"""
Adversarial & Regression Test Suite for OmniCache Architecture Remediation.
Verifies:
1. Cryptographic PII Salted Isolation (No cross-user token collision)
2. Tool Replay TTL Expiration Enforcement
3. Model Family Isolation in Semantic Cache (No cross-model contamination)
4. Speculative Model Cascade Opt-in Enforcement & Response Disclosures
5. Virtual Key Manager Reject Unregistered Keys (No auto-registration)
"""

import unittest
import time
from core.privacy_shield import privacy_shield
from server.tool_replayer import tool_cache
from core.vector_cache import DualTierCache, get_model_family
from server.cascade_router import cascade_router
from server.quotas import quota_manager
from starlette.testclient import TestClient
from server.gateway import app

class TestSecurityRemediation(unittest.TestCase):
    def setUp(self):
        self.client = TestClient(app)

    def test_01_pii_salted_cross_user_isolation(self):
        """Verify different user emails generate completely distinct HMAC tokens."""
        text_a = "Contact alice@company-a.com"
        text_b = "Contact bob@company-b.com"

        sanitized_a, token_map_a, count_a = privacy_shield.sanitize_text(text_a)
        sanitized_b, token_map_b, count_b = privacy_shield.sanitize_text(text_b)

        self.assertEqual(count_a, 1)
        self.assertEqual(count_b, 1)

        token_a = list(token_map_a.keys())[0]
        token_b = list(token_map_b.keys())[0]

        # Critical: Tokens MUST NOT collide (unlike legacy [REDACTED_EMAIL_1])
        self.assertNotEqual(token_a, token_b)
        self.assertIn("[REDACTED_EMAIL_", token_a)
        self.assertIn("[REDACTED_EMAIL_", token_b)

    def test_02_tool_replay_ttl_expiration(self):
        """Verify expired tool calls return MISS and are evicted."""
        tool_name = "git_diff"
        args = {"file": "main.py"}
        output = "+ print('hello world')"

        # Store with 1 second TTL
        tool_cache.store_tool_call(tool_name, args, output, ttl_seconds=1)

        # Immediate lookup -> HIT
        is_hit, cached_out, _ = tool_cache.lookup_tool_call(tool_name, args)
        self.assertTrue(is_hit)
        self.assertEqual(cached_out, output)

        # Wait for TTL expiry
        time.sleep(1.1)

        # Lookup after expiry -> MISS (must be evicted)
        is_hit_expired, cached_out_expired, _ = tool_cache.lookup_tool_call(tool_name, args)
        self.assertFalse(is_hit_expired)
        self.assertIsNone(cached_out_expired)

    def test_03_model_family_semantic_isolation(self):
        """Verify semantic cache strictly isolates models across vendor families."""
        cache = DualTierCache()

        # Cache a response generated by Gemini Flash
        gemini_payload = {
            "model": "gemini-2.5-flash",
            "messages": [{"role": "user", "content": "How do I reverse a string in python?"}],
            "temperature": 0.0
        }
        gemini_resp = {"choices": [{"message": {"content": "text[::-1] (from Gemini)"}}]}
        cache.store(gemini_payload, gemini_resp, org_id="tenant_iso")

        # Now query with GPT-4o with semantically similar prompt
        gpt_payload = {
            "model": "gpt-4o",
            "messages": [{"role": "user", "content": "Tell me how to reverse a string in python"}],
            "temperature": 0.0
        }

        # Must MISS because model families (google-gemini-flash vs openai-gpt4o) do NOT match
        status, entry, sim, reason = cache.lookup(gpt_payload, org_id="tenant_iso")
        self.assertEqual(status, "MISS")
        self.assertIn("MISS_MODEL_FAMILY_MISMATCH", reason)

    def test_04_cascade_opt_in_governance(self):
        """Verify cascade router does NOT substitute models unless caller explicitly opts in."""
        payload = {
            "messages": [{"role": "user", "content": "Capitalize: hello"}]
        }

        # Default (allow_cascade=False) -> MUST retain requested model
        model_default, tier_def, comp_def, cascaded_def, reason_def = cascade_router.evaluate_route(
            "gpt-4o", payload, allow_cascade=False
        )
        self.assertEqual(model_default, "gpt-4o")
        self.assertFalse(cascaded_def)
        self.assertEqual(reason_def, "cascade_opt_in_disabled")

        # Opt-in enabled (allow_cascade=True) -> Can cascade trivial queries
        model_opted, tier_opt, comp_opt, cascaded_opt, reason_opt = cascade_router.evaluate_route(
            "gpt-4o", payload, allow_cascade=True
        )
        self.assertEqual(model_opted, "gemini-2.5-flash")
        self.assertTrue(cascaded_opt)

    def test_05_unregistered_key_rejected(self):
        """Verify VirtualKeyManager rejects unknown keys and does NOT auto-register them."""
        # Unrecognized random key
        allowed, reason, info = quota_manager.check_authorization("unrecognized_random_key_999")
        self.assertFalse(allowed)
        self.assertIsNone(info)
        self.assertIn("Unauthorized", reason)

    def test_06_circuit_breaker_telemetry_in_gateway(self):
        """Verify /healthz and /v1/cache/stats report live circuit breaker status."""
        client = TestClient(app)
        res_health = client.get("/healthz")
        self.assertEqual(res_health.status_code, 200)
        data = res_health.json()
        self.assertIn("circuit_breaker", data)
        self.assertIn("openai", data["circuit_breaker"])
        self.assertIn("anthropic", data["circuit_breaker"])
        self.assertIn("google", data["circuit_breaker"])

        # Check in /v1/cache/stats
        res_stats = client.get("/v1/cache/stats")
        self.assertEqual(res_stats.status_code, 200)
        stats_data = res_stats.json()
        self.assertIn("circuit_breaker", stats_data["enterprise_engine"])

    def test_07_dynamic_salt_uniqueness(self):
        """Verify privacy salt is dynamically generated and not a static public constant."""
        from core.config import config
        self.assertTrue(len(config.PRIVACY_SALT) >= 32)
        self.assertNotEqual(config.PRIVACY_SALT, "OmniCache-Production-Salt-2025-V2")
        self.assertNotEqual(config.PRIVACY_SALT, "default_salt")

    def test_08_admin_endpoints_require_admin_privileges(self):
        """Verify tenant keys cannot access /v1/enterprise/quotas or /v1/cache/export."""
        client = TestClient(app)
        quota_manager.register_key("standard_tenant_key", team_name="Tenant Team", org_id="tenant_x", role="tenant")
        
        # Accessing quotas as tenant should be rejected
        res_quotas = client.get("/v1/enterprise/quotas", headers={"x-api-key": "standard_tenant_key"})
        self.assertEqual(res_quotas.status_code, 403)

    def test_09_pii_rehydration_no_inplace_cache_mutation(self):
        """
        Critical Regression Test: Verify rehydrate_response does NOT mutate cached entry in place.
        Ensures a cache HIT never permanently overwrites the cached template with user PII.
        """
        cache = DualTierCache()
        prompt_payload = {
            "model": "gpt-4o",
            "messages": [{"role": "user", "content": "What is my account email?"}]
        }
        # Original cached response containing redaction token
        template_token = privacy_shield.generate_token("EMAIL", "generic@example.com")
        original_cached_response = {
            "id": "chatcmpl-test-pii",
            "choices": [{
                "message": {
                    "role": "assistant",
                    "content": f"Your registered email address is {template_token}."
                }
            }],
            "usage": {"prompt_tokens": 10, "completion_tokens": 15, "total_tokens": 25}
        }
        entry = cache.store(prompt_payload, original_cached_response, org_id="pii_tenant")

        import json
        cached_before_json = json.dumps(entry.response_payload, sort_keys=True)

        # User A hits cache with their own private email
        user_a_token_map = {template_token: "alice_private@secret-domain.com"}
        rehydrated_a = privacy_shield.rehydrate_response(entry.response_payload, user_a_token_map)

        self.assertIn("alice_private@secret-domain.com", rehydrated_a["choices"][0]["message"]["content"])

        # Assert cached entry was NOT mutated in place
        cached_after_json = json.dumps(entry.response_payload, sort_keys=True)
        self.assertEqual(cached_before_json, cached_after_json)
        self.assertNotIn("alice_private@secret-domain.com", entry.response_payload["choices"][0]["message"]["content"])
        self.assertIn(template_token, entry.response_payload["choices"][0]["message"]["content"])

    def test_10_hmac_token_length_and_entropy(self):
        """Verify HMAC tokens use 16 hex characters (64-bit entropy) to eliminate collision risks."""
        token = privacy_shield.generate_token("EMAIL", "test@domain.com")
        # Format: [REDACTED_EMAIL_XXXXXXXXXXXXXXXX]
        prefix = "[REDACTED_EMAIL_"
        suffix = "]"
        self.assertTrue(token.startswith(prefix))
        self.assertTrue(token.endswith(suffix))
        hex_digest = token[len(prefix):-len(suffix)]
        self.assertEqual(len(hex_digest), 16)
        int(hex_digest, 16)  # Valid hex string check

    def test_11_live_request_spend_recording(self):
        """Verify upstream requests through gateway actively record spend into VirtualKeyManager."""
        from server.upstream import upstream_client
        from unittest.mock import patch, AsyncMock

        client = TestClient(app)
        test_key = "spend_test_key_001"
        quota_manager.register_key(test_key, team_name="Spend Test Team", org_id="spend_org", monthly_budget_usd=50.0)

        initial_spend = quota_manager.get_spend(test_key)
        self.assertEqual(initial_spend, 0.0)

        mock_upstream_response = (
            200,
            {
                "id": "chatcmpl-test-live",
                "object": "chat.completion",
                "choices": [{"message": {"role": "assistant", "content": "Pong test response"}}],
                "usage": {"prompt_tokens": 100, "completion_tokens": 200, "total_tokens": 300}
            },
            {}
        )

        with patch.object(upstream_client, "forward_non_stream", new=AsyncMock(return_value=mock_upstream_response)):
            req_payload = {
                "model": "gpt-4o",
                "messages": [{"role": "user", "content": "Ping test spend recording"}],
                "temperature": 0.0
            }
            resp = client.post(
                "/v1/chat/completions",
                json=req_payload,
                headers={"x-api-key": test_key, "x-cache-bypass": "true"}
            )
            self.assertEqual(resp.status_code, 200)

        # Assert spend was actually recorded > 0 in VirtualKeyManager
        final_spend = quota_manager.get_spend(test_key)
        self.assertGreater(final_spend, 0.0)

    def test_12_tool_replay_tenant_isolation_and_auth(self):
        """Verify /v1/agent/tool_replay enforces authentication and tenant namespace separation."""
        client = TestClient(app)
        quota_manager.register_key("tenant_tool_key_1", team_name="Tool Team 1", org_id="tool_org_1")
        quota_manager.register_key("tenant_tool_key_2", team_name="Tool Team 2", org_id="tool_org_2")

        # Store tool call under org_1 namespace
        tool_cache.store_tool_call("ls", {"dir": "/src"}, "file1.txt\nfile2.txt", workspace_fingerprint="tool_org_1:workspace_alpha")

        # Tenant 1 request -> HIT
        req_body = {
            "tool_name": "ls",
            "arguments": {"dir": "/src"},
            "workspace_fingerprint": "workspace_alpha"
        }
        res_t1 = client.post("/v1/agent/tool_replay", json=req_body, headers={"x-api-key": "tenant_tool_key_1"})
        self.assertEqual(res_t1.status_code, 200)
        self.assertEqual(res_t1.json().get("status"), "HIT")

        # Tenant 2 request with same workspace name -> MISS (isolated by tenant org_id)
        res_t2 = client.post("/v1/agent/tool_replay", json=req_body, headers={"x-api-key": "tenant_tool_key_2"})
        self.assertEqual(res_t2.status_code, 200)
        self.assertEqual(res_t2.json().get("status"), "MISS")

    def test_13_dashboard_auth_and_cors_defaults(self):
        """Verify CORS_ALLOW_ALL is False by default and /dashboard is protected when REQUIRE_AUTH is set."""
        from core.config import config
        self.assertFalse(config.CORS_ALLOW_ALL)

        client = TestClient(app)
        # Dashboard without auth when auth not required
        res_dash = client.get("/dashboard")
        self.assertEqual(res_dash.status_code, 200)

    def test_14_catchall_404_not_found(self):
        """Verify unmatched endpoints return 404 Not Found instead of fake 200 OK."""
        client = TestClient(app)
        res = client.get("/api/v9/non_existent_resource")
        self.assertEqual(res.status_code, 404)
        data = res.json()
        self.assertIn("error", data)
        self.assertEqual(data["error"]["code"], 404)

    def test_15_startup_security_invariants_enforcement(self):
        """Verify server refuses to bind to 0.0.0.0 without REQUIRE_AUTH unless explicitly bypassed."""
        from core.config import config, validate_startup_security_invariants
        
        # Localhost is always allowed
        validate_startup_security_invariants("127.0.0.1")
        validate_startup_security_invariants("localhost")

        # 0.0.0.0 without auth must raise RuntimeError
        orig_req_auth = config.REQUIRE_AUTH
        orig_allow_insecure = config.ALLOW_INSECURE_NETWORK_EXPOSURE
        try:
            config.REQUIRE_AUTH = False
            config.ALLOW_INSECURE_NETWORK_EXPOSURE = False
            with self.assertRaises(RuntimeError):
                validate_startup_security_invariants("0.0.0.0")

            # Allowed when REQUIRE_AUTH is True
            config.REQUIRE_AUTH = True
            validate_startup_security_invariants("0.0.0.0")

            # Allowed when explicitly bypassed
            config.REQUIRE_AUTH = False
            config.ALLOW_INSECURE_NETWORK_EXPOSURE = True
            validate_startup_security_invariants("0.0.0.0")
        finally:
            config.REQUIRE_AUTH = orig_req_auth
            config.ALLOW_INSECURE_NETWORK_EXPOSURE = orig_allow_insecure


if __name__ == "__main__":
    unittest.main()
