global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'omnicache-cluster'
    static_configs:
      - targets:
          - 'omnicache-1:8000'
          - 'omnicache-2:8000'
          - 'omnicache-3:8000'
        labels:
          cluster: 'omnicache-crdt-mesh'
          environment: 'production'
